version: '3'
services:
    web:
        image: nginx:alpine
        platform: linux/amd64
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8990:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: v1ll4n/php5.5.9-fpm-mysqli
        platform: linux/amd64
        restart: always
        volumes:
            # - "./etc/php/mysql.ini:/usr/local/etc/php/conf.d/mysql.ini:"
            # - "./etc/php/mysqli.ini:/usr/local/etc/php/conf.d/mysqli.ini:"
            # - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/php/php-fpm.ini:/php-fpm.ini"
            - "./web:/var/www/html"
        command: "php5-fpm -F -y /php-fpm.ini"
    myadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        platform: linux/amd64
        restart: always
        volumes:
            - "./data/wfp.sql:/docker-entrypoint-initdb.d/wfp.sql"
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
